import { jsPDF } from 'jspdf';

export const exportRagPdf = ({ query, response, alertLevel, district }) => {
  if (!response) return;

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;
  let y = 15;

  // Header Banner
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 28, 'F');

  doc.setTextColor(56, 189, 248); // cyan-400
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.text('SafeSlope NER AI — Disaster Advisory Report', margin, 12);

  doc.setTextColor(148, 163, 184); // slate-400
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.text('Smart India Hackathon (SIH 2026) | Grounded RAG Disaster Intelligence', margin, 18);

  y = 35;

  // Metadata Card Box
  doc.setFillColor(248, 250, 252); // slate-50
  doc.setDrawColor(226, 232, 240);
  doc.rect(margin, y, contentWidth, 32, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(30, 41, 59);

  doc.text('Target Location:', margin + 4, y + 6);
  doc.setFont('helvetica', 'normal');
  doc.text(`${district || 'Northeast India Region'}`, margin + 30, y + 6);

  doc.setFont('helvetica', 'bold');
  doc.text('Alert Level:', margin + 115, y + 6);
  if (alertLevel === 'CRITICAL') doc.setTextColor(225, 29, 72);
  else if (alertLevel === 'WARNING') doc.setTextColor(217, 119, 6);
  else doc.setTextColor(16, 185, 129);
  doc.text(`${alertLevel || 'NORMAL'}`, margin + 133, y + 6);

  doc.setTextColor(30, 41, 59);
  doc.setFont('helvetica', 'bold');
  doc.text('Model Engine:', margin + 4, y + 12);
  doc.setFont('helvetica', 'normal');
  doc.text(`${response.model_used || 'Google gemini-3.1-flash-lite'}`, margin + 30, y + 12);

  doc.setFont('helvetica', 'bold');
  doc.text('Generated At:', margin + 4, y + 18);
  doc.setFont('helvetica', 'normal');
  doc.text(`${new Date().toLocaleString()}`, margin + 30, y + 18);

  doc.setFont('helvetica', 'bold');
  doc.text('User Query:', margin + 4, y + 24);
  doc.setFont('helvetica', 'normal');
  const queryStr = `"${query || ''}"`;
  const queryLines = doc.splitTextToSize(queryStr, contentWidth - 25);
  doc.text(queryLines[0], margin + 22, y + 24);

  y += 40;

  // Section Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text('Official SOP & Field Guidance Response:', margin, y);
  y += 7;

  // Clean markdown formatting for clean text rendering in PDF
  let cleanAnswer = response.answer || '';
  cleanAnswer = cleanAnswer
    .replace(/^####?\s+/gm, '')
    .replace(/^###?\s+/gm, '')
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/`([^`]+)`/g, '$1');

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(51, 65, 85);

  const lines = doc.splitTextToSize(cleanAnswer, contentWidth);
  const lineHeight = 4.6;

  lines.forEach(line => {
    if (y + lineHeight > pageHeight - 25) {
      doc.addPage();
      y = 15;
    }
    doc.text(line, margin, y);
    y += lineHeight;
  });

  y += 6;

  // Cited Sources Box
  if (response.sources && response.sources.length > 0) {
    if (y + 20 > pageHeight - 25) {
      doc.addPage();
      y = 15;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9.5);
    doc.setTextColor(16, 185, 129);
    doc.text(`Verified Cited Source Manuals (${response.sources.length}):`, margin, y);
    y += 5;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(71, 85, 105);
    response.sources.forEach(src => {
      doc.text(`• ${src}`, margin + 3, y);
      y += 4.5;
    });
  }

  y += 6;
  if (y + 15 > pageHeight - 15) {
    doc.addPage();
    y = 15;
  }

  // Footer Emergency Disclaimer
  doc.setFillColor(254, 242, 242); // red-50
  doc.setDrawColor(254, 202, 202);
  doc.rect(margin, y, contentWidth, 14, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(185, 28, 28);
  doc.text('DISCLAIMER & EMERGENCY PROTOCOL:', margin + 3, y + 4.5);

  doc.setFont('helvetica', 'normal');
  const disclaimerText = 'Generated by SafeSlope NER AI based on NDMA Landslide SOP Manuals. In case of an immediate life-threatening emergency, contact local emergency services (108/112) or District DEOC immediately.';
  const disclaimerLines = doc.splitTextToSize(disclaimerText, contentWidth - 6);
  doc.text(disclaimerLines, margin + 3, y + 8.5);

  // Save the generated PDF
  const sanitizeName = (district || 'NER').replace(/[^a-zA-Z0-9]/g, '_');
  const filename = `SafeSlope_RAG_Advisory_${sanitizeName}_${Date.now()}.pdf`;
  doc.save(filename);
};
